### ISSUE TITLE
Wrong color for 403 errors

### ISSUE THREAD

**Issue by nvsneddon** [realprogrammer5000/doppelganger#1]
I noticed that 403 errors are shown with a green box. I think that the way you have this working is that you only have 404 errors make the box turn red. I would recommend changing that to have all 400 errors be red (or maybe a different color if you wish) instead of green because that could cause a user to think that their nickname is already taken on a website, when you only ran into a 403 forbidden error. 

By the way, I'm very impressed with your work. :)
![github-issue](https://user-images.githubusercontent.com/21978096/84605998-1ffcaa80-ae5f-11ea-8e6e-74bc3e7a28a2.png)

**Comment by pmaxhogan** [comment]
This should be fixed now.
